# Generated by Django 5.0.3 on 2024-04-09 13:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0002_remove_offdayrequest_previous_off_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=15, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "previous_jobs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "education",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "experience",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "skills",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "interests",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        size=None,
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
            ],
        ),
        migrations.DeleteModel(name="CV",),
    ]
