# Generated by Django 5.0.1 on 2024-03-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_options_and_more'),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.cv'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
